# Generated by Django 4.2.5 on 2023-09-26 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='DateOfService',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
